-- Per-user login bootstrap snapshots generated by the existing trusted server.
-- The first canary is intentionally limited to an active administrator with
-- all-student access because the response may contain full student metadata.

create table if not exists public.portal_login_bootstrap_snapshots (
  id uuid primary key default gen_random_uuid(),
  snapshot_key text not null unique,
  firebase_uid text not null,
  request_key text not null,
  schema_version text not null default 'v1',
  source_cache_version text not null default '',
  response_json jsonb not null default '{}'::jsonb,
  student_count integer not null default 0,
  notice_count integer not null default 0,
  refreshed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists portal_login_bootstrap_snapshots_lookup_idx
  on public.portal_login_bootstrap_snapshots(firebase_uid, request_key, schema_version, refreshed_at desc);

drop trigger if exists portal_login_bootstrap_snapshots_touch_updated_at
on public.portal_login_bootstrap_snapshots;
create trigger portal_login_bootstrap_snapshots_touch_updated_at
before update on public.portal_login_bootstrap_snapshots
for each row execute function public.touch_updated_at();

alter table public.portal_login_bootstrap_snapshots enable row level security;
revoke all on public.portal_login_bootstrap_snapshots from anon, authenticated;
grant select on public.portal_login_bootstrap_snapshots to authenticated;

drop policy if exists portal_login_bootstrap_snapshots_firebase_admin_self_select
on public.portal_login_bootstrap_snapshots;

create policy portal_login_bootstrap_snapshots_firebase_admin_self_select
on public.portal_login_bootstrap_snapshots
for select
to authenticated
using (
  (select auth.jwt() ->> 'iss') = 'https://securetoken.google.com/fir-lms-prod'
  and (select auth.jwt() ->> 'aud') = 'fir-lms-prod'
  and (select auth.jwt() ->> 'role') = 'authenticated'
  and firebase_uid = nullif((select auth.jwt() ->> 'sub'), '')
  and private.portal_can_read_all_student_stats()
);

comment on table public.portal_login_bootstrap_snapshots is
  'Short-lived per-user login bootstrap snapshots written by the trusted portal server.';
